version: "3.8"
services:
  totoapp-tutorial-db:
    env_file: ./.env
    image: "postgres:15"
    container_name: todoapp-tutorial-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
